version: '3'

services:
    app:
        build: .
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        # environment: 
        #     -   DB_HOST=db
        #     -   DB_DATABASE=laravel
        #     -   DB_USERNAME=root
        #     -   DB_PASSWORD=root
        container_name: app
        # volumes: 
        #     - .:/var/www
        networks: 
            - app-networks
        depends_on: 
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "8000:80"
        volumes:
            - .:/var/www
        networks: 
            - app-networks
        depends_on: 
            - app
        
    
    db:
        image: mysql:5.7
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            -   "3306:3306"
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        environment: 
            -   MYSQL_DATABASE=laravel
            -   MYSQL_ROOT_PASSWORD=root
            -   MYSQL_USER=root
        networks: 
            -   app-networks

    redis: 
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - app-networks

networks: 
    app-networks:
        driver: bridge
