apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: img-app-deployment
          # resources:
          #   requests:
          #     memory: "32Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 80

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-pass
          envFrom:
            - configMapRef:
                name: app-conf

          volumeMounts:
            - mountPath: /var/www/.env
              name: app-conf
              subPath: .env

      volumes:
        - name: app-conf
          configMap:
            name: app-conf
            items:
              - key: env
                path: .env
